Skip failing test_datetime_config_validation
The `ConfigTestCase.test_datetime_config_validation` test case fails on
Debian unstable:

======================================================================
FAIL: test_datetime_config_validation
(unit.utils.test_schema.ConfigTestCase)
[CPU:0.0%|MEM:54.9%]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit/utils/test_schema.py", line 848, in test_datetime_config_validation
    format_checker=jsonschema.FormatChecker())
AssertionError: ValidationError not raised

----------------------------------------------------------------------

Therefore skip this test until it gets fixed.

Bug: https://github.com/saltstack/salt/issues/55936
Signed-off-by: Benjamin Drung <benjamin.drung@cloud.ionos.com>