Skip failing HgPillarTestCase.test_base
The `HgPillarTestCase.test_base` test case fails:

```
test_base (unit.pillar.test_hg_pillar.HgPillarTestCase)
[CPU:9.5%|MEM:51.7%] check hg repo is imported correctly ... Füge
top.sls hinzu
Füge user.sls hinzu
18:08:29,187 [salt.template              :236 ][ERROR   ] The renderer
"yaml_jinja" is not available
18:08:29,187 [salt.loader                :650 ][CRITICAL] The renderer
yaml_jinja is unavailable, this error is often because the needed
software is unavailable
ERROR
Exception ignored in: <function Pillar.__del__ at 0x7f35cf6e5710>
Traceback (most recent call last):
  File "salt/pillar/__init__.py", line 1126, in __del__
    self.destroy()
  File "salt/pillar/__init__.py", line 1121, in destroy
    if self._closing:
AttributeError: 'Pillar' object has no attribute '_closing'

======================================================================
ERROR: test_base (unit.pillar.test_hg_pillar.HgPillarTestCase)
[CPU:13.2%|MEM:51.7%] check hg repo is imported correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit/pillar/test_hg_pillar.py", line 78, in test_base
    mypillar = hg_pillar.ext_pillar('*', None,
'file://{0}'.format(self.hg_repo_path))
  File "salt/pillar/hg_pillar.py", line 83, in ext_pillar
    pil = salt.pillar.Pillar(opts, __grains__, minion_id, envname)
  File "salt/pillar/__init__.py", line 390, in __init__
    self.rend = salt.loader.render(self.opts, self.functions)
  File "salt/loader.py", line 651, in render
    raise LoaderError(err)
salt.exceptions.LoaderError: The renderer yaml_jinja is unavailable,
this error is often because the needed software is unavailable
```

Therefore skip this test until it gets fixed.

Bug: https://github.com/saltstack/salt/issues/55935
Signed-off-by: Benjamin Drung <benjamin.drung@cloud.ionos.com>