loader: Fix loading grains with annotations
If custom grain modules use annotations, salt will fail to load them.
Example grain:

```
from typing import Dict

def example_grain() -> Dict[str, str]:
    return {"example": "42"}
```

`salt-call grains.items` will print this exception:

```
Failed to load grains defined in grain file ... in function <...>, error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 847, in grains
    parameters = salt.utils.args.get_function_argspec(funcs[key]).args
  File "/usr/lib/python3/dist-packages/salt/utils/args.py", line 271, in get_function_argspec
    aspec = _getargspec(func)
  File "/usr/lib/python3/dist-packages/salt/utils/args.py", line 40, in _getargspec
    "Function has keyword-only arguments or annotations"
ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them
```

Python recommends to use `inspect.signature` instead of
`inspect.getfullargspec` (which is only needs to maintain compatibility with
the Python 2 `inspect` module API). Since salt only supports Python 3, drop
using the wrapper function `get_function_argspec` and use `inspect.signature`
directly.

Forwarded: https://github.com/saltstack/salt/pull/60285
Signed-off-by: Benjamin Drung <benjamin.drung@ionos.com>