Fix parsing version of virtualenv
salt 3001 fails on Debian unstable:

```
======================================================================
ERROR: test_thin_dir (unit.utils.test_thin.SSHThinTestCase)
[CPU:0.0%|MEM:69.8%] Test the thin dir to make sure salt-call can run
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/unit/utils/test_thin.py", line 1312, in test_thin_dir
    with VirtualEnv() as venv:
  File "/<<PKGBUILDDIR>>/tests/support/helpers.py", line 1659, in __enter__
    self._create_virtualenv()
  File "/<<PKGBUILDDIR>>/tests/support/helpers.py", line 1718, in _create_virtualenv
    sminion.functions.virtualenv.create(
  File "/<<PKGBUILDDIR>>/salt/modules/virtualenv_mod.py", line 204, in create
    virtualenv_version_info = virtualenv_ver(venv_bin, user=user, **kwargs)
  File "/<<PKGBUILDDIR>>/salt/modules/virtualenv_mod.py", line 60, in virtualenv_ver
    [int(i) for i in version.split("rc")[0].split(".")]
  File "/<<PKGBUILDDIR>>/salt/modules/virtualenv_mod.py", line 60, in <listcomp>
    [int(i) for i in version.split("rc")[0].split(".")]
ValueError: invalid literal for int() with base 10: '23+ds'

----------------------------------------------------------------------
```

The python3-virtualenv package in Debian unstable has version `20.0.23+ds-1`.

Therefore strip the trailing `+ds` from the version before splitting it into
its integer parts.

Also remove duplicate calculation of `virtualenv_version_info`.

Fixes #57734
Forwarded: https://github.com/saltstack/salt/pull/57751
Signed-off-by: Benjamin Drung <benjamin.drung@cloud.ionos.com>